version: '3.8'

services:
  api:
    image: api
    container_name: api
    ports:
      - "8085:8085"   
    environment:
      SPRING_PROFILES_ACTIVE=prod
    networks:
      - spring-boot-net

  car:
    image: car
    container_name: car
    ports:
      - "8081:8081"   
    environment:
      SPRING_PROFILES_ACTIVE=prod
    networks:
      - spring-boot-net

  data:
    image: data
    container_name: data
    ports:
      - "8086:8086"   
    environment:
      SPRING_PROFILES_ACTIVE=prod
    networks:
      - spring-boot-net


networks:
  spring-boot-net:
    external: true